CREATE DATABASE Cineplex_IN4AV;
USE Cineplex_IN4AV;

CREATE TABLE Usuarios  (
ID_Usuario INT(25) AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Usuario VARCHAR(100) NOT NULL UNIQUE,
Clave VARCHAR(20) NOT NULL,
Rol VARCHAR (50) NOT NULL
);

CREATE TABLE Peliculas (
ID_Pelicula INT(25) AUTO_INCREMENT PRIMARY KEY,
Titulo VARCHAR(100) NOT NULL,
Genero VARCHAR(70) NOT NULL,
Duracion INT(255) NOT NULL,
Categoria VARCHAR(70) NOT NULL,
Director VARCHAR(100) NOT NULL,
Poster VARCHAR(250)
);
